### ISSUE TITLE
Backdrop wrong

### ISSUE THREAD

**Issue by JerichoZG** [BloodDragon2580/Portable#1]
2x Portable\Common.lua:92: attempt to call method 'SetBackdrop' (a nil value)
[string "@Portable\Common.lua"]:92: in function `SetFrameStyle'
[string "@Portable\Main.lua"]:391: in function `CreateUI_Sizer'
[string "@Portable\Main.lua"]:294: in function `CreateUI'
[string "@Portable\Main.lua"]:250: in function `?'
[string "@Portable\Main.lua"]:225: in function <Portable\Main.lua:223>

Locals:
self = <table> {
 Slash_Help = <function> defined @Portable\Main.lua:1435
 Do_ReorderList = <function> defined @Portable\Reorder.lua:186
 UpdateUI_ButtonGrid = <function> defined @Portable\Main.lua:779
 print = <function> defined @Portable\Common.lua:16
 UpdateUI_Broker = <function> defined @Portable\Broker.lua:126
 SetFrameStyle = <function> defined @Portable\Common.lua:91
 ui = PortableUIFrame {
 }
 DoScript_OnEnter = <function> defined @Portable\Main.lua:1347
 CreateUI_Container = <function> defined @Portable\Main.lua:426
 CreateUI_Reorder = <function> defined @Portable\Reorder.lua:67
 MAX_BUTTONS = 14
 CreateUI_Sizer = <function> defined @Portable\Main.lua:386
 Options = <table> {
 }
 DoScript_OnClick = <function> defined @Portable\Main.lua:1367
 UpdateUI_MinimapIcon = <function> defined @Portable\MinimapIcon.lua:48
 HideUI_Broker = <function> defined @Portable\Broker.lua:353
 UpdateUI_ShowTextures = <function> defined @Portable\Main.lua:618
 UpdateUI = <function> defined @Portable\Main.lua:487
 CreateUI_MinimapIcon = <function> defined @Portable\MinimapIcon.lua:35
 GetAddonInfo = <function> defined @Portable\Common.lua:33
 MakeTooltip = <function> defined @Portable\Common.lua:72
 Helper_ResetLearning = <function> defined @Portable\Main.lua:1224
 LDB = <table> {
 }
 Helper_EscapeToClose = <function> defined @Portable\Main.lua:1311
 Helper_ShowConfig = <function> defined @Portable\Main.lua:1303
 Helper_GetToolbarSize = <function> defined @Portable\Main.lua:1288
 Helper_IsInBags = <function> defined @Portable\Main.lua:1274
 UpdateUI_TextStyle = <function> defined @Portable\Main.lua:1106
 Helper_UpdateBrokerInfoText = <function> defined @Portable\Broker.lua:321
 Helper_IsSpecialFrame = <function> defined @Portable\Main.lua:1326
 Helper_LearnOrder = <function> defined @Portable\Main.lua:1158
 UpdateUI_FrameSize = <function> defined @Portable\Main.lua:496
 Helper_ShowDisabled = <function> defined @Portable\Main.lua:1131
 MakeText = <function> defined @Portable\Common.lua:62
 UpdateUI_ButtonActions = <function> defined @Portable\Main.lua:974
 UpdateUI_FrameStyle = <function> defined @Portable\Main.lua:643
 Apply_Reorder = <function> defined @Portable\Reorder.lua:49
 UpdateUI_IconSizeFrame = <function> defined @Portable\Main.lua:561
 Helper_AdjustFont = <function> defined @Portable\Main.lua:1146
 hSpell = <table> {
 }
 db = <table> {
 }
 L = <table> {
 }
 ShowUI_Broker = <function> defined @Portable\Broker.lua:285
 brokerFeed = <table> {
 }
 DoScript_OnLeave = <function> defined @Portable\Main.lua:1357
 CreateUI_Frame = <function> defined @Portable\Main.lua:302
 Helper_ResetOrder = <function> defined @Portable\Main.lua:1249
 SetFontSize = <function> defined @Portable\Common.lua:105
 ShowReorderUI = <function> defined @Portable\Reorder.lua:21
 CreateUI = <function> defined @Portable\Main.lua:290
 UpdateUI_Container = <function> defined @Portable\Main.lua:609
 aSpell = <table> {
 }
 CreateUI_Broker = <function> defined @Portable\Broker.lua:61
 UpdateOptions = <function> defined @Portable\Main.lua:277
 EventFrame = PortableEventFrame {
 }
 Helper_BrokerWatchMouse = <function> defined @Portable\Broker.lua:334
 CreateUI_Buttons = <function> defined @Portable\Main.lua:432
 lsm = <table> {
 }
 MakeButton = <function> defined @Por

**Comment by BloodDragon2580** [comment]
Work on it soon

**Comment by JerichoZG** [comment]
Thanks for the update,try this(temporary solution):

```
local function fixSetBackdrop(frame,backdrop)
if frame.SetBackdrop then return frame:SetBackdrop(backdrop) end
Mixin(frame,BackdropTemplateMixin)
frame:SetScript("OnSizeChanged",frame.OnBackdropSizeChanged,0)
frame:SetBackdrop(backdrop)
frame:OnBackdropLoaded()
end
```
![image](https://user-images.githubusercontent.com/58062394/98320895-d3d52100-201e-11eb-9d46-2355b11b716d.png)
[https://bbs.nga.cn/read.php?tid=23729978](url)

Your Addon has made life easier for many mage players. Thank you again for your work.

**Comment by BloodDragon2580** [comment]
When you have a fix make a pull request please.

**Comment by BloodDragon2580** [comment]
Is fixed now.
