### ISSUE TITLE
Bug: Spell button issues in main window

### ISSUE THREAD

**Issue by nancikennedy** [BloodDragon2580/Portable#11]
- ~~Silvermoon City button does not have the proper border texture _when the Icon Artwork Style is set to "Simple Square"_. Need to check the equivalent Alliance spell.~~ Moving this to it's own issue.
- Button layouts (Options:Button Icons:Icon Layout:Icon Layout drop-down menu) other than "Simple Rows" are flaky
-- This may be due to the addition of the new Valdrakken spell, which is not being suppressed when unknown. Moving it, to anything other than last place in the manual order window, causes either the last button in the list to disappear OR to become "unpinned" from the frame.

**Comment by nancikennedy** [comment]
Notes for further investigation, because my brain is tired...

- hSpell/aSpell contain 16 possible "destinations"
- My char only knows 15, because the new one (Valdrakken) isn't available yet for me to learn
- The manual ordering window is not greying out Valdrakken, so I can change it's order
- Moving Valdrakken "up" places it in an index order position above 16 AND causes the last destination to either disappear completely or become unattached/bugged in the frame.
- Is this bug caused by the fact that I've created an order that forces a spell I don't know into the frame?
**- Should the unknown spell be greyed out in the manual ordering window, to compensate?**

**Comment by nancikennedy** [comment]
Tested this, and the behavior has changed a bit but is still buggy.

- The orphan button floating around unattached to the Portable frame seems to have been resolved
- [In all layouts] Valdrakken is not greyed out and mousing over it activates the hover texture. Clicking does nothing other than close Portable.
- Reordering is still problematic in all layouts but Simple Rows:
  - With Valdrakken anywhere but last in the reorder list, the buttons sorts properly according to the list BUT the last spell disappears completely.

  - With Valdrakken at the bottom of the Reorder list
    - The Valdrakken icon stacks over the icon of the spell in last place (Reorder list). I did get the reverse, but can't replicate it.
    - The Valdrakken text stacks under the text of the spell in last place (Reorder list)
     
      ![Portable Button Issue with Valdrakken](https://user-images.githubusercontent.com/8207666/199390309-0a95f85a-f4c5-40db-887d-865b28caab9c.JPG)
    - Based on the Icon Layout chosen, new weirdness is happening.

     Left Priority: ![Portable Priority Left](https://user-images.githubusercontent.com/8207666/199391697-a1753a74-0c2c-4eac-9160-70303a5e3f9f.JPG)

     Right Priority: ![Portable Priority Right](https://user-images.githubusercontent.com/8207666/199393255-5623b951-9d5e-41f2-a3fd-165ae79fe220.JPG)

     Center of Attention: ![Center of Attention](https://user-images.githubusercontent.com/8207666/199393286-4856f11e-b56c-48ed-ad86-e2351a715b1b.JPG)

     Left Look at Me!: ![Look at Me Left](https://user-images.githubusercontent.com/8207666/199393315-2b1e31b3-6327-4981-a97b-50bdd8775ee0.JPG)

     Right Look at Me!: ![Look at Me Right](https://user-images.githubusercontent.com/8207666/199393376-62098da2-35a9-49ad-b1c2-7b2e4bef0482.JPG)

**Comment by BloodDragon2580** [comment]
Most of problems should now fixed.
