### ISSUE TITLE
Bug: LDB spells not firing

### ISSUE THREAD

**Issue by nancikennedy** [BloodDragon2580/Portable#12]
When the LDB does populate with the list of known spells, they may not actually do anything when clicked (left or right)

**Comment by BloodDragon2580** [comment]
Check line 77 on Broker.lua. Change it from 

**me.broker[button].sab:RegisterForClicks("LeftButtonUp", "RightButtonUp")**

to

**me.broker[button].sab:RegisterForClicks("LeftButtonDown", "RightButtonDown")**

Your Fix^^

**Comment by nancikennedy** [comment]
LOL

**Comment by BloodDragon2580** [comment]
It works?

**Comment by nancikennedy** [comment]
Yes. Yes, it does. :)

**Comment by BloodDragon2580** [comment]
Ok nice I will add it when iam at home.

**Comment by BloodDragon2580** [comment]
Fixed in next Update.

**Comment by BloodDragon2580** [comment]
Fix uploaded to github but dont to curse at this moment:

https://github.com/BloodDragon2580/Portable/commit/757d54560b852ed6d46df821e918f8a88416f1f6
