### ISSUE TITLE
Bug: LDB Mouseover Triggering Problem

### ISSUE THREAD

**Issue by nancikennedy** [BloodDragon2580/Portable#13]
When moving the mouse over the LDB tooltip, the mouse is triggering the mouseover effect of elements that are underneath the LDB tooltip.

**Comment by BloodDragon2580** [comment]
Should fix the problems with the DataBroker first. At least for now.

https://github.com/BloodDragon2580/Portable/commit/c20629e30fa2ba0de99dc569247bd3c02e5de345

**Comment by nancikennedy** [comment]
This appears to have made it worse. Previously, the underlying elements information showed underneath the Portable tooltip. Now they appear above it, and the tooltip has all the basic LDB text related to the tooltip itself....but no spell information. Reloading does seem to fix it either.

![Portable LDB](https://user-images.githubusercontent.com/8207666/199389253-31d28c6d-54a6-4d3c-a44d-d2e4e190a586.JPG)

**Comment by BloodDragon2580** [comment]
I have remove the teleports from data Broker it only should open the frame from portable and options.
