### ISSUE TITLE
New Version button casting issue....

### ISSUE THREAD

**Issue by nancikennedy** [BloodDragon2580/Portable#15]
I took a gander at the diffs from the latest version and the one immediately previous to see what you changed...

It looks like when you changed the Secure Button Template to XXXButtonUp from XXXButtonDown, you forgot to change the mouseover broker note to reflect  that the new command to make it work should be /console ActionButtonUseKeyDown 0, as it still says to use "1" and anyone who was using the previous versions after having set it with /console ActionButtonUseKeyDown 1 is now thinking it's broken.

https://github.com/BloodDragon2580/Portable/blob/da83641fb7cc916b3eb843d92e9620e6db7ca026/Portable/Broker.lua#L201

:)

**Comment by BloodDragon2580** [comment]
Have change the command in the settings now to /console ActionButtonUseKeyDown 0 and have remove all older commands.
I have make in the comments and at the Description on curse a messege with the correct command.

Thx you
