### ISSUE TITLE
Initialize Error with new Patch

### ISSUE THREAD

**Issue by nancikennedy** [BloodDragon2580/Portable#17]
On Retail, using Portable v11.9, it's throwing this error:

7x Portable/Main.lua:177: attempt to call method 'Initialize' (a nil value)
[string "@Portable/Main.lua"]:177: in function `?'
[string "@Portable/Main.lua"]:151: in function <Portable/Main.lua:149>

Locals:
self = PortableEventFrame {
}
addonName = "Portable"
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to call method 'Initialize' (a nil value)"
myName = "Portable"
Event = PortableEventFrame {
}
me = <table> {
 MAX_BUTTONS = 17
 ui = PortableUIFrame {
 }
 Options = <table> {
 }
 LDB = <table> {
 }
 db = <table> {
 }
 L = <table> {
 }
 hSpell = <table> {
 }
 brokerFeed = <table> {
 }
 aSpell = <table> {
 }
 EventFrame = PortableEventFrame {
 }
 lsm = <table> {
 }
}
defaults = <table> {
 profile = <table> {
 }
}
L = <table> {
 Portable = "|cff0088ffPortable|cff808080: |r"
}

**Comment by nancikennedy** [comment]
There were two more errors, but I figured out what the problem was and it was all inter-related and made them all go away.

Common.lua, lines 26 and 20 GetAddOnMetadata needs to be updated to C_AddOns.GetAddOnMetadata

Common.lua, Main.lua & Options.lua: Replaced all occurrences of GetAddonInfo with GetAddOnInfo

**Comment by BloodDragon2580** [comment]
should be fixed now:
https://github.com/BloodDragon2580/Portable/commit/edee814595fac21081011b90a877070c4b41abff
I have now uploaded it to curse, can you test it later to see if it works?

**Comment by nancikennedy** [comment]
Tested and getting no errors
