### ISSUE TITLE
Picture Problem

### ISSUE THREAD

**Issue by JerichoZG** [BloodDragon2580/Portable#2]
a little issue 
![image](https://user-images.githubusercontent.com/58062394/98549830-4a4f7880-22d6-11eb-8f3d-5f661a430759.png)

**Comment by BloodDragon2580** [comment]
What settings you use?

- Priority (LEFT)
- Priority (RIGHT)
- Center of Attention
- Look at Me (LEFT)
- Look at Me (RIGHT)
- Simple Rows

**Comment by BloodDragon2580** [comment]
Have fix a other Button Error, please check the new version 5.6.

**Comment by BloodDragon2580** [comment]
Any News about the Error?

**Comment by JerichoZG** [comment]
![image](https://user-images.githubusercontent.com/58062394/98624704-51639e80-2349-11eb-8d52-daa49aa1dead.png)
Well Done! Thanks so much！
PS:Would you please add “ancient Dalaran” if the player had learned ？
I've tried adding it myself before, but it didn't work out

**Comment by BloodDragon2580** [comment]
I would not like to add the Dalaran portal since we already have 2 Dalaran portals in it.
I'll think about it. The most important thing is that the translations are slowly being finished ^^.

**Comment by BloodDragon2580** [comment]
So i will close this issue for now.
