### ISSUE TITLE
Hearthstone toys

### ISSUE THREAD

**Issue by Tuhljin** [BloodDragon2580/Portable#4]
The button to use your hearthstone doesn't work with the hearthstone toys -- Eternal Traveler's Hearthstone, Tome of Town Portal, Greatfather Winter's Hearthstone, etc.

I don't carry a normal hearthstone since relying only on the toys frees up a slot in my bags, so when I click the button in Portable to use my hearthstone, nothing happens.

Ideally, there would be some sort of config option where you can choose which hearthstones the player wants to use, including the normal one and any toys, and Portable would randomly select one of the ones you've selected. (If someone only wants to use a specific hearthstone, they'd just have the one selected from the list.)

**Comment by BloodDragon2580** [comment]
At the moment that's not planned.
In the course of time I'll see if I include it.
