### ISSUE TITLE
Bug: Buttons don't cast spells

### ISSUE THREAD

**Issue by nancikennedy** [BloodDragon2580/Portable#7]
None of the buttons cast spells at the moment. I suspect this is based on the API changes Blizzard made to the "hold-and-release function on keypress" functionality so it's now Drakthyr only.

**Comment by nancikennedy** [comment]
I figured it out, and did a pull request.

**Comment by BloodDragon2580** [comment]
Very nice my friend. I love you. :)

**Comment by BloodDragon2580** [comment]
Hey do you have Discord? You can add me, so we can write there: BloodDragon#6210

**Comment by nancikennedy** [comment]
Yeah.
