### ISSUE TITLE
Bug: Random LDB failure

### ISSUE THREAD

**Issue by nancikennedy** [BloodDragon2580/Portable#9]
Occasionally, the LDB plugin will not populate its contents and will show a tallish blank popup with a very thin width. Reloading a few times usually fixed this.

**Comment by nancikennedy** [comment]
This is now fixed

**Comment by nancikennedy** [comment]
Wrong Issue closed...have not confirmed that this has been squashed yet.

**Comment by BloodDragon2580** [comment]
Should fix the problems with the DataBroker first. At least for now.

https://github.com/BloodDragon2580/Portable/commit/c20629e30fa2ba0de99dc569247bd3c02e5de345
